export const PERMISSIONS = {
  // Platform
  USERS_READ: 'platform.users.read',
  USERS_INVITE: 'platform.users.invite',
  USERS_MANAGE: 'platform.users.manage',
  ORGS_MANAGE: 'platform.organizations.manage',
  BRANCHES_READ: 'platform.branches.read',
  BRANCHES_MANAGE: 'platform.branches.manage',
  ROLES_READ: 'platform.roles.read',
  SUBSCRIPTION_READ: 'platform.subscription.read',
  BILLING_READ: 'platform.billing.read',
  SETTINGS_MANAGE: 'platform.settings.manage',
  AUDIT_READ: 'platform.audit.read',
  // POS Clothing — runtime
  POS_CLOTHING_SELL: 'pos_clothing.sell',
  POS_CLOTHING_MANAGE: 'pos_clothing.manage',
  // POS Clothing — catalog
  POS_CLOTHING_PRODUCTS: 'pos_clothing.products',
  POS_CLOTHING_PRODUCTS_CREATE: 'pos_clothing.products.create',
  POS_CLOTHING_PRODUCTS_EDIT: 'pos_clothing.products.edit',
  POS_CLOTHING_CATEGORIES: 'pos_clothing.categories',
  POS_CLOTHING_VARIANTS: 'pos_clothing.variants',
  POS_CLOTHING_BRANDS: 'pos_clothing.brands',
  POS_CLOTHING_SIZE_GUIDES: 'pos_clothing.size_guides',
  POS_CLOTHING_BARCODES: 'pos_clothing.barcodes',
  // POS Clothing — seasons / collections
  POS_CLOTHING_SEASONS: 'pos_clothing.seasons',
  POS_CLOTHING_COLLECTIONS: 'pos_clothing.collections',
  // POS Clothing — inventory & purchasing
  POS_CLOTHING_INVENTORY: 'pos_clothing.inventory',
  POS_CLOTHING_INVENTORY_ADJUST: 'pos_clothing.inventory.adjust',
  POS_CLOTHING_STOCK_TRANSFERS: 'pos_clothing.stock_transfers',
  POS_CLOTHING_PURCHASE_ORDERS: 'pos_clothing.purchase_orders',
  POS_CLOTHING_SUPPLIERS: 'pos_clothing.suppliers',
  // POS Clothing — customer & loyalty
  POS_CLOTHING_CUSTOMERS: 'pos_clothing.customers',
  POS_CLOTHING_LOYALTY: 'pos_clothing.loyalty',
  POS_CLOTHING_STORE_CREDIT: 'pos_clothing.store_credit',
  POS_CLOTHING_GIFT_CARDS: 'pos_clothing.gift_cards',
  // POS Clothing — pricing / promotions
  POS_CLOTHING_PRICING: 'pos_clothing.pricing',
  POS_CLOTHING_PROMOTIONS: 'pos_clothing.promotions',
  POS_CLOTHING_MARKDOWNS: 'pos_clothing.markdowns',
  // POS Clothing — services
  POS_CLOTHING_FITTING_HOLDS: 'pos_clothing.fitting_holds',
  POS_CLOTHING_ALTERATIONS: 'pos_clothing.alterations',
  POS_CLOTHING_TAILORS: 'pos_clothing.tailors',
  POS_CLOTHING_LAYAWAY: 'pos_clothing.layaway',
  POS_CLOTHING_LAYAWAY_FORFEIT: 'pos_clothing.layaway.forfeit',
  // POS Clothing — outlet / hardware / staff
  POS_CLOTHING_BRANCHES: 'pos_clothing.branches',
  POS_CLOTHING_DEVICES: 'pos_clothing.devices',
  POS_CLOTHING_SHIFTS: 'pos_clothing.shifts',
  POS_CLOTHING_TAX: 'pos_clothing.tax',
  POS_CLOTHING_SETTINGS: 'pos_clothing.settings',
  POS_CLOTHING_QUICK_KEYS: 'pos_clothing.quick_keys',
  // POS Clothing — runtime ops
  POS_CLOTHING_TRANSACTIONS: 'pos_clothing.transactions',
  POS_CLOTHING_RETURNS: 'pos_clothing.returns',
  // POS Clothing — reporting & ops
  POS_CLOTHING_REPORTS: 'pos_clothing.reports',
  POS_CLOTHING_DASHBOARD: 'pos_clothing.dashboard',
  POS_CLOTHING_AUDIT: 'pos_clothing.audit',
  POS_CLOTHING_ALERTS: 'pos_clothing.alerts',
  // POS Shop — admin
  POS_SHOP_PRODUCTS: 'pos_shop.products',
  POS_SHOP_CATEGORIES: 'pos_shop.categories',
  POS_SHOP_BARCODES: 'pos_shop.barcodes',
  POS_SHOP_INVENTORY: 'pos_shop.inventory',
  POS_SHOP_STOCK_TRANSFERS: 'pos_shop.stock_transfers',
  POS_SHOP_PURCHASE_ORDERS: 'pos_shop.purchase_orders',
  POS_SHOP_SUPPLIERS: 'pos_shop.suppliers',
  POS_SHOP_CUSTOMERS: 'pos_shop.customers',
  POS_SHOP_LOYALTY: 'pos_shop.loyalty',
  POS_SHOP_PRICING: 'pos_shop.pricing',
  POS_SHOP_PROMOTIONS: 'pos_shop.promotions',
  POS_SHOP_BRANCHES: 'pos_shop.branches',
  POS_SHOP_DEVICES: 'pos_shop.devices',
  POS_SHOP_SHIFTS: 'pos_shop.shifts',
  POS_SHOP_TAX: 'pos_shop.tax',
  POS_SHOP_SETTINGS: 'pos_shop.settings',
  POS_SHOP_REPORTS: 'pos_shop.reports',
  POS_SHOP_DASHBOARD: 'pos_shop.dashboard',
  POS_SHOP_AUDIT: 'pos_shop.audit',
  POS_SHOP_ALERTS: 'pos_shop.alerts',
  POS_SHOP_HOLDS: 'pos_shop.holds',
  POS_SHOP_RETURNS: 'pos_shop.returns',
  // POS Shop — runtime
  POS_SHOP_SELL: 'pos_shop.sell',
  POS_SHOP_REFUND: 'pos_shop.refund',
  POS_SHOP_MANAGE_SESSION: 'pos_shop.manage_session',
  POS_SHOP_VIEW_REPORTS: 'pos_shop.view_reports',
  POS_SHOP_MANAGE: 'pos_shop.manage',
  // POS Food Service
  POS_FOOD_SERVICE_ORDERS: 'pos_food_service.orders',
  POS_FOOD_SERVICE_QUEUE: 'pos_food_service.queue',
  POS_FOOD_SERVICE_TENDER: 'pos_food_service.tender',
  POS_FOOD_SERVICE_MANAGE: 'pos_food_service.manage',
  POS_FOOD_SERVICE_MENU: 'pos_food_service.menu',
  POS_FOOD_SERVICE_MENU_CREATE: 'pos_food_service.menu.create',
  POS_FOOD_SERVICE_MENU_EDIT: 'pos_food_service.menu.edit',
  POS_FOOD_SERVICE_MENU_CATEGORIES_CREATE:
    'pos_food_service.menu.categories.create',
  POS_FOOD_SERVICE_MENU_CATEGORIES_EDIT:
    'pos_food_service.menu.categories.edit',
  POS_FOOD_SERVICE_REGISTER_READ: 'pos_food_service.register.read',
  POS_FOOD_SERVICE_CATEGORIES: 'pos_food_service.categories',
  POS_FOOD_SERVICE_MODIFIERS: 'pos_food_service.modifiers',
  POS_FOOD_SERVICE_REPORTS: 'pos_food_service.reports',
  POS_FOOD_SERVICE_SETTINGS: 'pos_food_service.settings',
  POS_FOOD_SERVICE_INVENTORY: 'pos_food_service.inventory',
  POS_FOOD_SERVICE_SUPPLIERS: 'pos_food_service.suppliers',
  POS_FOOD_SERVICE_STOCK_TRANSFERS: 'pos_food_service.stock_transfers',
  POS_FOOD_SERVICE_BRANCHES: 'pos_food_service.branches',
  POS_FOOD_SERVICE_TABLES: 'pos_food_service.tables',
  POS_FOOD_SERVICE_CUSTOMERS: 'pos_food_service.customers',
  POS_FOOD_SERVICE_STAFF: 'pos_food_service.staff',
  // Ads Manager
  ADS_VIEW: 'ads_manager.view',
  ADS_CONNECT_ACCOUNTS: 'ads_manager.connect_accounts',
  ADS_MANAGE_CAMPAIGNS: 'ads_manager.manage_campaigns',
  ADS_VIEW_REPORTS: 'ads_manager.view_reports',
  // Chat Manager
  CHAT_VIEW_INBOX: 'chat_manager.view_inbox',
  CHAT_REPLY: 'chat_manager.reply',
  CHAT_ASSIGN: 'chat_manager.assign',
  CHAT_MANAGE_CHANNELS: 'chat_manager.manage_channels',
  CHAT_VIEW_ANALYTICS: 'chat_manager.view_analytics',
  // Ecommerce
  ECOMMERCE_MANAGE_STORE: 'ecommerce.manage_store',
  ECOMMERCE_MANAGE_ORDERS: 'ecommerce.manage_orders',
  ECOMMERCE_FULFILL: 'ecommerce.fulfill',
  ECOMMERCE_VIEW_ANALYTICS: 'ecommerce.view_analytics',
  // Inventory
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_TRANSFER: 'inventory.transfer',
  INVENTORY_APPROVE_TRANSFER: 'inventory.approve_transfer',
  INVENTORY_VIEW_LEDGER: 'inventory.view_ledger',
} as const
