export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  ACCEPT_INVITE: '/accept-invite',
  DASHBOARD: '/dashboard',
  // Platform
  USERS: '/platform/users',
  ROLES: '/platform/roles',
  BRANCHES: '/platform/branches',
  SUBSCRIPTION: '/platform/subscription',
  BILLING: '/platform/billing',
  SETTINGS: '/platform/settings',
  AUDIT_LOGS: '/platform/audit-logs',
  ME: '/platform/me',
  NOTIFICATIONS: '/notifications',
  // Modules
  POS_SHOP: '/pos/shop',
  POS_FOOD_SERVICE: '/pos/food-service',
  ECOMMERCE: '/ecommerce',
  INVENTORY: '/inventory',
  ADS: '/ads',
  CHAT: '/chat',
  REPORTS: '/reports',
} as const
